export const seedProducts = [
  {
    slug: "noir-amber",
    name: "Noir Amber",
    category: "Scented Candles",
    scent: "Amber + Vanilla",
    description: "Topel vecerni vonj z bogatim premium podpisom.",
    price: 34,
    stock: 18,
    etaDays: 5,
    isTop: true,
    isNew: false,
    salePercent: 0
  },
  {
    slug: "velvet-fig",
    name: "Velvet Fig",
    category: "Scented Candles",
    scent: "Fig + Sandalwood",
    description: "Sodoben sadni profil za eleganten ritual doma.",
    price: 32,
    stock: 8,
    etaDays: 4,
    isTop: true,
    isNew: false,
    salePercent: 10
  },
  {
    slug: "golden-musk",
    name: "Golden Musk",
    category: "Limited Editions",
    scent: "Musk + Cedar",
    description: "Globok, umirjen in prefinjen vonj.",
    price: 39,
    stock: 0,
    etaDays: 7,
    isTop: true,
    isNew: false,
    salePercent: 0
  },
  {
    slug: "cashmere-bloom",
    name: "Cashmere Bloom",
    category: "Decor Candles",
    scent: "White Tea + Floral",
    description: "Nezen clean-luxe obcutek za dnevni ambient.",
    price: 31,
    stock: 14,
    etaDays: 4,
    isTop: false,
    isNew: true,
    salePercent: 0
  },
  {
    slug: "runway-smoke",
    name: "Runway Smoke",
    category: "Fashion Candles",
    scent: "Smoked Oud",
    description: "Editorial statement sveca za dizajnerski dom.",
    price: 43,
    stock: 4,
    etaDays: 6,
    isTop: false,
    isNew: false,
    salePercent: 15
  },
  {
    slug: "halloween-noir",
    name: "Halloween Noir",
    category: "Limited Editions",
    scent: "Pumpkin + Tonka",
    description: "Sezonska jesenska kolekcija z mocnim karakterjem.",
    price: 37,
    stock: 10,
    etaDays: 5,
    isTop: true,
    isNew: true,
    salePercent: 0
  },
  {
    slug: "black-friday-box",
    name: "Black Friday Box",
    category: "Limited Editions",
    scent: "Mix Collection",
    description: "Paket 3 svec z ugodnejso ceno za akcijsko obdobje.",
    price: 79,
    stock: 16,
    etaDays: 4,
    isTop: true,
    isNew: true,
    salePercent: 20
  },
  {
    slug: "custom-label-jar",
    name: "Custom Label Jar",
    category: "Personalization",
    scent: "Custom scent",
    description: "Osnova za personalizirane serije z napisom in logotipom.",
    price: 49,
    stock: 6,
    etaDays: 7,
    isTop: false,
    isNew: true,
    salePercent: 0
  },
  {
    slug: "marble-candle-stand",
    name: "Marble Candle Stand",
    category: "Accessories",
    scent: "Accessory",
    description: "Premium podstavek za svece v crno-zlatem tonu.",
    price: 24,
    stock: 24,
    etaDays: 3,
    isTop: false,
    isNew: false,
    salePercent: 0
  },
  {
    slug: "jet-lighter-pro",
    name: "Jet Lighter Pro",
    category: "Accessories",
    scent: "Accessory",
    description: "Elegantni refillable vzigalnik za premium ritual.",
    price: 19,
    stock: 31,
    etaDays: 2,
    isTop: false,
    isNew: false,
    salePercent: 0
  },
  {
    slug: "beauty-tray-gold",
    name: "Beauty Tray Gold",
    category: "Beauty Trays",
    scent: "Accessory",
    description: "Dekorativni pladenj za svece, parfum in jewelry setup.",
    price: 29,
    stock: 12,
    etaDays: 4,
    isTop: false,
    isNew: true,
    salePercent: 0
  },
  {
    slug: "saromen-tee-black",
    name: "SAROMEN Tee Black",
    category: "Merch",
    scent: "Textile",
    description: "Minimalna premium majica z zlatim logotipom SAROMEN.",
    price: 36,
    stock: 22,
    etaDays: 4,
    isTop: false,
    isNew: true,
    salePercent: 0
  },
  {
    slug: "saromen-hoodie-noir",
    name: "SAROMEN Hoodie Noir",
    category: "Merch",
    scent: "Textile",
    description: "Pulover s kapuco, heavy cotton, luxury black-gold branding.",
    price: 68,
    stock: 14,
    etaDays: 5,
    isTop: true,
    isNew: true,
    salePercent: 10
  }
];

export const seedCoupons = [
  { code: "SARA10", percent: 10, minAmount: 0 },
  { code: "DOMEN15", percent: 15, minAmount: 60 },
  { code: "LOVE20", percent: 20, minAmount: 120 }
];
